### ISSUE TITLE
job.title Tag and Awesome Icons

### ISSUE THREAD

**Issue by emallickhossain** [svmiller/svmiller.github.io#1]
Hi Steven! 

First off, thanks so much for making your Jekyll code publicly available and for your blog posts on RMarkdown and Beamer! I've been using your code to get my own site set up. 

1. Helping you update your site as you get promoted: in your `footer.html` file, your position is hard-coded as "Assistant Professor" instead of referencing your `job.title` in your `_config.yml` file. I had to change `job.title` to `jobtitle` in the `_config.yml` title, but then you can just throw

`	        <li>{{ site.jobtitle }}</li>`

in your `footer.html` file instead of the hard-coded "Assistant Professor"

2. You might already know this, but using Awesome Icons will help clean up your `footer.html` file for your social media links as well ([source](https://blog.r3bl.me/en/simple-social-media-links-jekyll/)). If you add 

`<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">`

to your `head.html` file, then you can just use the following to render the social media icons

```
          {% if site.linkedin_username %}
            <li>
              <a href="https://linkedin.com/in/{{ site.linkedin_username }}">
                <i class="fa fa-linkedin" style="color:gray"></i> LinkedIn
              </a>
            </li>
          {% endif %}
```

I hope that helps and I hope you rise through the ranks quickly! I hope you're having a great semester and thanks again for the great stuff you've posted!

**Comment by svmiller** [comment]
@Both useful information, actually. I didn't know about the second point. It also didn't dawn on me until I looked at the code just now that my previous attempts to include `job.title` in the footer likely choked because I used a period in the config file.

Thanks for the contribution!
